### ISSUE TITLE
Minor issues encountered in README when testing it with Mirte

### ISSUE THREAD

**Issue by jkooij** [MartijnWisse/mirte_workshop#5]
Hi, having played with the Mirte now, I encountered some very minor issues on the README that could be fixed:

## A. Section 2.1, Connect to the Wifi

The readme says the Wifi network has a name `mirte-XXXXXX`, but the first letter should be capitalized: `Mirte-XXXXXX`

## B. Section 5. First robot motions

The assignment, says

> change the `x` value to `0.3` again and press `Enter` to publish the message:

Note that the Twist message has two `x` values (one for `linear` and one for `angular`), so it could be better specified of you mean one, the other, or either one.

## C. Section 4.3 Testing

> "Let's test if it all works with the very underwhelming command"

I would still explicitly state what you should see happen upon success, and if the answer is "nothing", then state what one should see upon failure. Otherwise it is a bit unclear how this is a test.

## D. More of a suggestion: Make section numbering unique throughout a single documentation file

The README has multiple sections 1, 2, 3 etc., once for "Getting Started", and once for "Getting the workshop software on the robot".
For communicating about steps, such as the "bug" report above, it may be more useful of all sections in the same document are unique. You could add a level to the hierarchy, and make Getting Started section 1, and have it have subsections 1.1, 1.2, etc. Then Getting the Workshop... becomes section 2, with subsections 2.1, 2.2, etc.

**Comment by MartijnWisse** [comment]
all fixed.
